export type PaymentMethod = 'flutterwave' | 'stripe' | 'razorpay' | 'mercadopago' | 'paytabs' | 'crypto'

export interface Country {
  name: string
  code: string
  currency: string
  symbol: string
  methods: PaymentMethod[]
}

export const COUNTRIES: Country[] = [
  { name: 'Afghanistan', code: 'AF', currency: 'AFN', symbol: '؋', methods: ['crypto'] },
  { name: 'Albania', code: 'AL', currency: 'ALL', symbol: 'L', methods: ['stripe', 'crypto'] },
  { name: 'Algeria', code: 'DZ', currency: 'DZD', symbol: 'دج', methods: ['flutterwave', 'crypto'] },
  { name: 'Angola', code: 'AO', currency: 'AOA', symbol: 'Kz', methods: ['flutterwave', 'crypto'] },
  { name: 'Argentina', code: 'AR', currency: 'ARS', symbol: '$', methods: ['mercadopago', 'crypto'] },
  { name: 'Armenia', code: 'AM', currency: 'AMD', symbol: '֏', methods: ['stripe', 'crypto'] },
  { name: 'Australia', code: 'AU', currency: 'AUD', symbol: 'A$', methods: ['stripe', 'crypto'] },
  { name: 'Austria', code: 'AT', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'Azerbaijan', code: 'AZ', currency: 'AZN', symbol: '₼', methods: ['crypto'] },
  { name: 'Bahrain', code: 'BH', currency: 'BHD', symbol: 'BD', methods: ['paytabs', 'crypto'] },
  { name: 'Bangladesh', code: 'BD', currency: 'BDT', symbol: '৳', methods: ['razorpay', 'crypto'] },
  { name: 'Belgium', code: 'BE', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'Benin', code: 'BJ', currency: 'XOF', symbol: 'Fr', methods: ['flutterwave', 'crypto'] },
  { name: 'Bolivia', code: 'BO', currency: 'BOB', symbol: 'Bs', methods: ['mercadopago', 'crypto'] },
  { name: 'Bosnia and Herzegovina', code: 'BA', currency: 'BAM', symbol: 'KM', methods: ['stripe', 'crypto'] },
  { name: 'Botswana', code: 'BW', currency: 'BWP', symbol: 'P', methods: ['flutterwave', 'crypto'] },
  { name: 'Brazil', code: 'BR', currency: 'BRL', symbol: 'R$', methods: ['mercadopago', 'stripe', 'crypto'] },
  { name: 'Bulgaria', code: 'BG', currency: 'BGN', symbol: 'лв', methods: ['stripe', 'crypto'] },
  { name: 'Burkina Faso', code: 'BF', currency: 'XOF', symbol: 'Fr', methods: ['flutterwave', 'crypto'] },
  { name: 'Burundi', code: 'BI', currency: 'BIF', symbol: 'Fr', methods: ['flutterwave', 'crypto'] },
  { name: 'Cambodia', code: 'KH', currency: 'KHR', symbol: '៛', methods: ['crypto'] },
  { name: 'Cameroon', code: 'CM', currency: 'XAF', symbol: 'Fr', methods: ['flutterwave', 'crypto'] },
  { name: 'Canada', code: 'CA', currency: 'CAD', symbol: 'C$', methods: ['stripe', 'crypto'] },
  { name: 'Chad', code: 'TD', currency: 'XAF', symbol: 'Fr', methods: ['flutterwave', 'crypto'] },
  { name: 'Chile', code: 'CL', currency: 'CLP', symbol: '$', methods: ['mercadopago', 'crypto'] },
  { name: 'Colombia', code: 'CO', currency: 'COP', symbol: '$', methods: ['mercadopago', 'crypto'] },
  { name: 'Congo', code: 'CG', currency: 'XAF', symbol: 'Fr', methods: ['flutterwave', 'crypto'] },
  { name: 'Costa Rica', code: 'CR', currency: 'CRC', symbol: '₡', methods: ['mercadopago', 'crypto'] },
  { name: 'Croatia', code: 'HR', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'Cyprus', code: 'CY', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'Czech Republic', code: 'CZ', currency: 'CZK', symbol: 'Kč', methods: ['stripe', 'crypto'] },
  { name: 'Denmark', code: 'DK', currency: 'DKK', symbol: 'kr', methods: ['stripe', 'crypto'] },
  { name: 'Dominican Republic', code: 'DO', currency: 'DOP', symbol: 'RD$', methods: ['mercadopago', 'crypto'] },
  { name: 'Ecuador', code: 'EC', currency: 'USD', symbol: '$', methods: ['mercadopago', 'crypto'] },
  { name: 'Egypt', code: 'EG', currency: 'EGP', symbol: '£', methods: ['flutterwave', 'paytabs', 'crypto'] },
  { name: 'El Salvador', code: 'SV', currency: 'USD', symbol: '$', methods: ['mercadopago', 'crypto'] },
  { name: 'Estonia', code: 'EE', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'Ethiopia', code: 'ET', currency: 'ETB', symbol: 'Br', methods: ['flutterwave', 'crypto'] },
  { name: 'Finland', code: 'FI', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'France', code: 'FR', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'Gabon', code: 'GA', currency: 'XAF', symbol: 'Fr', methods: ['flutterwave', 'crypto'] },
  { name: 'Gambia', code: 'GM', currency: 'GMD', symbol: 'D', methods: ['flutterwave', 'crypto'] },
  { name: 'Georgia', code: 'GE', currency: 'GEL', symbol: '₾', methods: ['stripe', 'crypto'] },
  { name: 'Germany', code: 'DE', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'Ghana', code: 'GH', currency: 'GHS', symbol: 'GH₵', methods: ['flutterwave', 'crypto'] },
  { name: 'Greece', code: 'GR', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'Guatemala', code: 'GT', currency: 'GTQ', symbol: 'Q', methods: ['mercadopago', 'crypto'] },
  { name: 'Guinea', code: 'GN', currency: 'GNF', symbol: 'Fr', methods: ['flutterwave', 'crypto'] },
  { name: 'Honduras', code: 'HN', currency: 'HNL', symbol: 'L', methods: ['mercadopago', 'crypto'] },
  { name: 'Hungary', code: 'HU', currency: 'HUF', symbol: 'Ft', methods: ['stripe', 'crypto'] },
  { name: 'Iceland', code: 'IS', currency: 'ISK', symbol: 'kr', methods: ['stripe', 'crypto'] },
  { name: 'India', code: 'IN', currency: 'INR', symbol: '₹', methods: ['razorpay', 'crypto'] },
  { name: 'Indonesia', code: 'ID', currency: 'IDR', symbol: 'Rp', methods: ['crypto'] },
  { name: 'Ireland', code: 'IE', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'Israel', code: 'IL', currency: 'ILS', symbol: '₪', methods: ['stripe', 'crypto'] },
  { name: 'Italy', code: 'IT', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'Ivory Coast', code: 'CI', currency: 'XOF', symbol: 'Fr', methods: ['flutterwave', 'crypto'] },
  { name: 'Jamaica', code: 'JM', currency: 'JMD', symbol: 'J$', methods: ['stripe', 'crypto'] },
  { name: 'Japan', code: 'JP', currency: 'JPY', symbol: '¥', methods: ['stripe', 'crypto'] },
  { name: 'Jordan', code: 'JO', currency: 'JOD', symbol: 'JD', methods: ['paytabs', 'crypto'] },
  { name: 'Kazakhstan', code: 'KZ', currency: 'KZT', symbol: '₸', methods: ['crypto'] },
  { name: 'Kenya', code: 'KE', currency: 'KES', symbol: 'KSh', methods: ['flutterwave', 'crypto'] },
  { name: 'Kosovo', code: 'XK', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'Kuwait', code: 'KW', currency: 'KWD', symbol: 'KD', methods: ['paytabs', 'crypto'] },
  { name: 'Latvia', code: 'LV', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'Lebanon', code: 'LB', currency: 'LBP', symbol: 'ل.ل', methods: ['paytabs', 'crypto'] },
  { name: 'Lesotho', code: 'LS', currency: 'LSL', symbol: 'L', methods: ['flutterwave', 'crypto'] },
  { name: 'Liberia', code: 'LR', currency: 'LRD', symbol: '$', methods: ['flutterwave', 'crypto'] },
  { name: 'Libya', code: 'LY', currency: 'LYD', symbol: 'LD', methods: ['crypto'] },
  { name: 'Lithuania', code: 'LT', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'Luxembourg', code: 'LU', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'Madagascar', code: 'MG', currency: 'MGA', symbol: 'Ar', methods: ['flutterwave', 'crypto'] },
  { name: 'Malawi', code: 'MW', currency: 'MWK', symbol: 'MK', methods: ['flutterwave', 'crypto'] },
  { name: 'Malaysia', code: 'MY', currency: 'MYR', symbol: 'RM', methods: ['crypto'] },
  { name: 'Mali', code: 'ML', currency: 'XOF', symbol: 'Fr', methods: ['flutterwave', 'crypto'] },
  { name: 'Malta', code: 'MT', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'Mauritania', code: 'MR', currency: 'MRU', symbol: 'UM', methods: ['crypto'] },
  { name: 'Mauritius', code: 'MU', currency: 'MUR', symbol: '₨', methods: ['flutterwave', 'crypto'] },
  { name: 'Mexico', code: 'MX', currency: 'MXN', symbol: '$', methods: ['mercadopago', 'stripe', 'crypto'] },
  { name: 'Moldova', code: 'MD', currency: 'MDL', symbol: 'L', methods: ['stripe', 'crypto'] },
  { name: 'Morocco', code: 'MA', currency: 'MAD', symbol: 'MAD', methods: ['flutterwave', 'paytabs', 'crypto'] },
  { name: 'Mozambique', code: 'MZ', currency: 'MZN', symbol: 'MT', methods: ['flutterwave', 'crypto'] },
  { name: 'Namibia', code: 'NA', currency: 'NAD', symbol: '$', methods: ['flutterwave', 'crypto'] },
  { name: 'Nepal', code: 'NP', currency: 'NPR', symbol: '₨', methods: ['razorpay', 'crypto'] },
  { name: 'Netherlands', code: 'NL', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'New Zealand', code: 'NZ', currency: 'NZD', symbol: 'NZ$', methods: ['stripe', 'crypto'] },
  { name: 'Nicaragua', code: 'NI', currency: 'NIO', symbol: 'C$', methods: ['mercadopago', 'crypto'] },
  { name: 'Niger', code: 'NE', currency: 'XOF', symbol: 'Fr', methods: ['flutterwave', 'crypto'] },
  { name: 'Nigeria', code: 'NG', currency: 'NGN', symbol: '₦', methods: ['flutterwave', 'crypto'] },
  { name: 'Norway', code: 'NO', currency: 'NOK', symbol: 'kr', methods: ['stripe', 'crypto'] },
  { name: 'Oman', code: 'OM', currency: 'OMR', symbol: 'ر.ع.', methods: ['paytabs', 'crypto'] },
  { name: 'Pakistan', code: 'PK', currency: 'PKR', symbol: '₨', methods: ['razorpay', 'crypto'] },
  { name: 'Panama', code: 'PA', currency: 'PAB', symbol: 'B/.', methods: ['mercadopago', 'crypto'] },
  { name: 'Paraguay', code: 'PY', currency: 'PYG', symbol: '₲', methods: ['mercadopago', 'crypto'] },
  { name: 'Peru', code: 'PE', currency: 'PEN', symbol: 'S/', methods: ['mercadopago', 'crypto'] },
  { name: 'Philippines', code: 'PH', currency: 'PHP', symbol: '₱', methods: ['crypto'] },
  { name: 'Poland', code: 'PL', currency: 'PLN', symbol: 'zł', methods: ['stripe', 'crypto'] },
  { name: 'Portugal', code: 'PT', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'Qatar', code: 'QA', currency: 'QAR', symbol: 'ر.ق', methods: ['paytabs', 'crypto'] },
  { name: 'Romania', code: 'RO', currency: 'RON', symbol: 'lei', methods: ['stripe', 'crypto'] },
  { name: 'Rwanda', code: 'RW', currency: 'RWF', symbol: 'Fr', methods: ['flutterwave', 'crypto'] },
  { name: 'Saudi Arabia', code: 'SA', currency: 'SAR', symbol: '﷼', methods: ['paytabs', 'crypto'] },
  { name: 'Senegal', code: 'SN', currency: 'XOF', symbol: 'Fr', methods: ['flutterwave', 'crypto'] },
  { name: 'Serbia', code: 'RS', currency: 'RSD', symbol: 'din', methods: ['stripe', 'crypto'] },
  { name: 'Sierra Leone', code: 'SL', currency: 'SLL', symbol: 'Le', methods: ['flutterwave', 'crypto'] },
  { name: 'Singapore', code: 'SG', currency: 'SGD', symbol: 'S$', methods: ['stripe', 'crypto'] },
  { name: 'Slovakia', code: 'SK', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'Slovenia', code: 'SI', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'Somalia', code: 'SO', currency: 'SOS', symbol: 'Sh', methods: ['crypto'] },
  { name: 'South Africa', code: 'ZA', currency: 'ZAR', symbol: 'R', methods: ['flutterwave', 'stripe', 'crypto'] },
  { name: 'South Korea', code: 'KR', currency: 'KRW', symbol: '₩', methods: ['stripe', 'crypto'] },
  { name: 'Spain', code: 'ES', currency: 'EUR', symbol: '€', methods: ['stripe', 'crypto'] },
  { name: 'Sri Lanka', code: 'LK', currency: 'LKR', symbol: '₨', methods: ['razorpay', 'crypto'] },
  { name: 'Sudan', code: 'SD', currency: 'SDG', symbol: 'ج.س.', methods: ['crypto'] },
  { name: 'Sweden', code: 'SE', currency: 'SEK', symbol: 'kr', methods: ['stripe', 'crypto'] },
  { name: 'Switzerland', code: 'CH', currency: 'CHF', symbol: 'Fr', methods: ['stripe', 'crypto'] },
  { name: 'Taiwan', code: 'TW', currency: 'TWD', symbol: 'NT$', methods: ['stripe', 'crypto'] },
  { name: 'Tanzania', code: 'TZ', currency: 'TZS', symbol: 'Sh', methods: ['flutterwave', 'crypto'] },
  { name: 'Thailand', code: 'TH', currency: 'THB', symbol: '฿', methods: ['crypto'] },
  { name: 'Togo', code: 'TG', currency: 'XOF', symbol: 'Fr', methods: ['flutterwave', 'crypto'] },
  { name: 'Tunisia', code: 'TN', currency: 'TND', symbol: 'DT', methods: ['paytabs', 'crypto'] },
  { name: 'Turkey', code: 'TR', currency: 'TRY', symbol: '₺', methods: ['stripe', 'crypto'] },
  { name: 'Uganda', code: 'UG', currency: 'UGX', symbol: 'Sh', methods: ['flutterwave', 'crypto'] },
  { name: 'Ukraine', code: 'UA', currency: 'UAH', symbol: '₴', methods: ['stripe', 'crypto'] },
  { name: 'United Arab Emirates', code: 'AE', currency: 'AED', symbol: 'د.إ', methods: ['paytabs', 'stripe', 'crypto'] },
  { name: 'United Kingdom', code: 'GB', currency: 'GBP', symbol: '£', methods: ['stripe', 'crypto'] },
  { name: 'United States', code: 'US', currency: 'USD', symbol: '$', methods: ['stripe', 'crypto'] },
  { name: 'Uruguay', code: 'UY', currency: 'UYU', symbol: '$U', methods: ['mercadopago', 'crypto'] },
  { name: 'Venezuela', code: 'VE', currency: 'VES', symbol: 'Bs.S', methods: ['mercadopago', 'crypto'] },
  { name: 'Vietnam', code: 'VN', currency: 'VND', symbol: '₫', methods: ['crypto'] },
  { name: 'Zambia', code: 'ZM', currency: 'ZMW', symbol: 'ZK', methods: ['flutterwave', 'crypto'] },
  { name: 'Zimbabwe', code: 'ZW', currency: 'ZWL', symbol: '$', methods: ['flutterwave', 'crypto'] },
]

export const METHOD_LABELS: Record<PaymentMethod, string> = {
  flutterwave: 'Flutterwave (Bank / Mobile Money)',
  stripe: 'Card Payment (Stripe)',
  razorpay: 'Razorpay (UPI / Card)',
  mercadopago: 'Mercado Pago',
  paytabs: 'PayTabs',
  crypto: 'Pay with Crypto',
}

export const METHOD_ICONS: Record<PaymentMethod, string> = {
  flutterwave: '🏦',
  stripe: '💳',
  razorpay: '💸',
  mercadopago: '🛒',
  paytabs: '🔐',
  crypto: '₿',
}
